name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Production:
    runs-on: self-hosted
    environment:
      name: Production
      url: https://tiktofiy.com

    strategy:
      matrix:
        node-version: [18.6.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies and build'
        run: |
          yarn install
          yarn build

      - name: 'Restart pm2'
        run: |
          npx pm2 restart 0 --update-env
          npx pm2 save
