name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Production:
    runs-on: self-hosted
    environment: Production

    strategy:
      matrix:
        node-version: [17.9.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Create .env file and put the secrets inside'
        run: |
          touch .env
          echo SHAZAM_API_KEY=${{ secrets.SHAZAM_API_KEY }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env

      - name: 'Install dependencies and build'
        run: |
          yarn install
          yarn build

      - name: 'Restart pm2'
        run: |
          npx pm2 restart 0 --update-env
          npx pm2 save
