name: Redeploy the app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn build
